from enum import Enum

class GameType(Enum):
    PRESEASON_GAME_TYPE = 1
    SEASON_GAME_TYPE = 2
    POSTSEASON_GAME_TYPE = 3
    
valid_game_types = [GameType.SEASON_GAME_TYPE]

class ErrorCode(Enum):
    DB_LOAD_TRADE_ERROR = 1
    DB_ADJUST_BALANCE_ERROR = 2

    TEAM_DOES_NOT_EXIST = 100

    ACCOUNT_DOES_NOT_EXIST = 200
    ACCOUNT_ALREADY_EXISTS = 201
    ACCOUNT_BALANCE_NOT_VALID = 202
    ACCOUNT_HOLDINGS_NOT_VALID = 203